#!bin/sh

echo "Welcome to setup master, choose the branch:"
echo "	alpinehost"
echo "	dailyarcher"
read branch
git checkout $branch
echo "(NEED TO BE ROOT!) Press ENTER to proceed with the install script..."
read && sh setup-post
