#!/bin/ash

# Install X, base-devel files/tools, audio, and everything virtualization
setup-xorg-base dbus-x11 xrandr
apk add g++ zsh htop make shadow ncurses \
	libx11-dev libxft-dev libxinerama-dev \
	xf86-video-intel xf86-input-synaptics \
	qemu qemu-img qemu-modules qemu-system-x86_64 \
	libvirt virt-viewer virt-install libvirt-daemon \
	pulseaudio pulseaudio-alsa alsa-plugins-pulse \
	alsa-utils alsa-lib alsaconf umix \
	ttf-liberation ttf-font-awesome \
	sudo gvim file ranger

# Enable services
rc-update add libvirtd
rc-update add alsa
rc-update add dbus

# Compile executables
mkdir executables
cd executables

	# DWM
	git clone https://github.com/MLquest8/dwm.git && cd dwm
	git checkout alpinehost
	make install
	cd ..

	# DMENU
	git clone https://github.com/MLquest8/dmenu.git && cd dmenu
	git checkout alpinehost
	make install
	cd ..

	# ST
	git clone https://github.com/MLquest8/st.git && cd st
	git checkout alpinehost
	make install
	cd ..

# Back to main directory
cd ..

# Add a user and give them privileges
echo "Add a new user: " && read username
useradd -m -g users -G wheel,libvirt,video,audio,input -s /bin/zsh $username
echo "$username ALL=(ALL) ALL" > /etc/sudoers.d/$username
chmod 0440 /etc/sudoers.d/$username
passwd $username

# Copy X configs
cp -a -f xfiles/. /etc/X11/xorg.conf.d

# Copy and link dotfiles
homedir=$(awk -F: -v v="$username" '{if ($1==v) print $6}' /etc/passwd)
mkdir -p $homedir/.config/$username/
cp -a -f dotfiles/. $homedir/.config/$username/
ln -sf $homedir/.config/$username/.* $homedir/

# Fix unicode defaults
sed -i s/#unicode="NO"\n\n#/#unicode="NO"\n\nunicode="YES"\n\n#/ /etc/rc.conf

# Install OhMyZsh
su $username && cd $homedir
zsh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="bira"/' .zshrc
sed -i 's/plugins=(git)/plugins=(git sudo)/' .zshrc

# Final words
echo "===================================================="
echo "Enter $username password to reboot..." && sudo reboot
echo "===================================================="
