#!/bin/sh

imgsize="50G"
imgfmt="qcow2"
imgname="vmArcher"
imgpalloc="full"
imgdirectory="$HOME"
imgfulladdress="$imgdirectory/$imgname.$imgfmt"

qemu-img create -f $imgfmt -o preallocation=$imgpalloc $imgfulladdress $imgsize

vmname="Archer"
vmdesc="Arch daily driver"
vmostype="Linux"
vmosvariant="archlinux"
vminstaller="ISO/archlinux-2021.09.01-x86_64.iso"
vmdiskpath=$imgfulladdress
vmvcpus="2"
vmram="2560"
vmarch="x86_64"
vmtype="kvm"
vmgraphics="spice"
vmnetwork="network:default"

sudo virt-install \
	--name="$vmname" \
	--description="$vmdesc" \
	--os-type="$vmostype" \
	--os-variant="$vmosvariant" \
	--cdrom="$vminstaller" \
	--disk path="$vmdiskpath" \
	--vcpus="$vmvcpus" \
	--ram="$vmram" \
	--check-cpu \
	--arch="$vmarch" \
	--virt-type="$vmtype" \
	--graphics="$vmgraphics" \
	--network="$vmnetwork"
