#!/bin/sh

imgsize="15G"
imgfmt="qcow2"
imgname="vmAlpine"
imgpalloc="metadata"
imgdirectory="$HOME"
imgfulladdress="$imgdirectory/$imgname.$imgfmt"

qemu-img create -f $imgfmt -o preallocation=$imgpalloc $imgfulladdress $imgsize

vmname="Alpine"
vmdesc="Alpine for testing"
vmostype="Linux"
vmosvariant="alpinelinux3.14"
vminstaller="ISO/alpine-extended-3.14.2-x86_64.iso"
vmdiskpath=$imgfulladdress
vmvcpus="1"
vmram="1024"
vmarch="x86_64"
vmtype="kvm"
vmgraphics="spice"
vmnetwork="network:default"

sudo virt-install \
	--name="$vmname" \
	--description="$vmdesc" \
	--os-type="$vmostype" \
	--os-variant="$vmosvariant" \
	--cdrom="$vminstaller" \
	--disk path="$vmdiskpath" \
	--vcpus="$vmvcpus" \
	--ram="$vmram" \
	--check-cpu \
	--arch="$vmarch" \
	--virt-type="$vmtype" \
	--graphics="$vmgraphics" \
	--network="$vmnetwork"
