#!/bin/sh

imgsize="50G"
imgfmt="qcow2"
imgname="vmWin10"
imgpalloc="full"
imgdirectory="$HOME"
imgfulladdress="$imgdirectory/$imgname.$imgfmt"

qemu-img create -f $imgfmt -o preallocation=$imgpalloc $imgfulladdress $imgsize

vmname="Windows10"
vmdesc="Windows10 workstation"
vmostype="Windows"
vmosvariant="win10"
vminstaller="ISO/windows_10_pro_en-US_v1909_x64.iso"
vmdiskpath=$imgfulladdress
vmvcpus="2"
vmram="3456"
vmarch="x86_64"
vmtype="kvm"
vmgraphics="spice"
vmnetwork="network:default"

sudo virt-install \
	--name="$vmname" \
	--description="$vmdesc" \
	--os-type="$vmostype" \
	--os-variant="$vmosvariant" \
	--cdrom="$vminstaller" \
	--disk path="$vmdiskpath" \
	--vcpus="$vmvcpus" \
	--ram="$vmram" \
	--check-cpu \
	--arch="$vmarch" \
	--virt-type="$vmtype" \
	--graphics="$vmgraphics" \
	--network="$vmnetwork"
