#!/bin/bash

# Make sure only root can run the script
if [[ $EUID -ne 0 ]]; then
	echo "Elevated permissions are required to run full system update!" 1>&2
	exit 1
fi

UPDATEKEYRING=false
if [ -d /etc/pacman.d/gnupg ]; then
	while true; do
		read -p "Would you like to update the keyring first? [y/N]: " choice
		case "$choice" in
		[Yy]* )
			UPDATEKEYRING=true
			break
			;;
		[Nn]* )
			UPDATEKEYRING=false
			break
			;;
		"" )
			# Go with the defaults
			break
			;;
		* )
			echo "Please enter 'y' for yes or 'n' for no."
			;;
		esac
	done
fi

if [ "$UPDATEKEYRING" = true ]; then
	# Clear backups if they already exist
	if [ -d /etc/pacman.d/gnupg.bak ]; then
		rm -rf /etc/pacman.d/gnupg.bak
	fi

	# Backup package keys
	if mv /etc/pacman.d/gnupg{,.bak}; then
		echo "Backup of package keys successful."
	fi

	# Update keys first and then the packages
	pacman -Sy --needed archlinux-keyring
	pacman-key --init && pacman-key -u
	pacman-key --populate
fi

# Full system update
pacman -Syu

# Remove orphaned packages
ORPHANEDPACKAGES=$(pacman -Qtdq)
if [ -n "$ORPHANEDPACKAGES" ]; then
	pacman -Rns $ORPHANEDPACKAGES
fi

# Clear cache
pacman -Sc

UPDATEMIRRORLIST=true
if [ -f /etc/pacman.d/mirrorlist.pacnew ]; then
	while true; do
		read -p "Would you like to update the mirror list? [Y/n]: " choice
		case "$choice" in
		[Yy]* )
			UPDATEMIRRORLIST=true
			break
			;;
		[Nn]* )
			UPDATEMIRRORLIST=false
			break
			;;
		"" )
			# Go with the defaults
			break
			;;
		* )
			echo "Please enter 'y' for yes or 'n' for no."
			;;
		esac
	done
fi


if [ "$UPDATEMIRRORLIST" = true ]; then
	if [ -s /etc/pacman.d/mirrorlist.pacnew ]; then
		sed -i 's/#S/S/g' /etc/pacman.d/mirrorlist.pacnew
		sed -n '/## Germany/, /## Greece/{ /## Greece/!p }' /etc/pacman.d/mirrorlist.pacnew > /etc/pacman.d/mirrorlist
		rm /etc/pacman.d/mirrorlist.pacnew
	fi
fi
